name = "medium-backend"
main = "src/index.ts"
compatibility_date = "2024-10-09"
compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNThjNjk1YTctYmM3MS00MzVjLThhYTktYTUxNTE2ZjI0NmM5IiwidGVuYW50X2lkIjoiMDNkM2M3OGUxNDQzZTNkNjBkYzVjNTdmZWY0M2RiMWU0NWNiNGMwZmVhMWY4Njc3NGYyM2EzOWM2MGIwMTk0OCIsImludGVybmFsX3NlY3JldCI6IjM2ZmJkMmY4LWUwMDAtNDU5Mi1iYzYwLTk5MDkyYjAzNWRiMiJ9.4LPrMgR7143t48d5CWKO3JTsEGgDWIgpIcLhyn1rR6c"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

